### ISSUE TITLE
Parameter is_dhcp_server_enabled in arubaoss_vlan module

### ISSUE THREAD

**Issue by tchiapuziowong** [aruba/aruba-ansible-modules#10]
This parameter causes VLAN creation failures in platforms that do not support DHCPserver options on a VLAN. When set to True, this value fails to enable DHCP server on a VLAN. Raising this issue until module parameter fixed.

**Comment by falkheiland** [comment]
is this going to be fixed? it is still not possible to get a dhcp address on a vlan.

**Comment by tchiapuziowong** [comment]
Hello! This commit should resolve your issue, please pull, reinstall the modules, and try again! Please let me know if you're still seeing the issue!
d0d660a
