### ISSUE TITLE
NTP  example playbook API Issue ?

### ISSUE THREAD

**Issue by mac0815** [aruba/aruba-ansible-modules#102]
Hi
used the nap playbook example for IAP´s and get the following error
oot@ansible:~# ansible-playbook play2.yml -i /etc/ansible/hosts -vvv
ansible-playbook 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: play2.yml **********************************************************************************************************************************************************************************************************************************
1 plays in play2.yml
Read vars_file 'variables.yml'
Read vars_file 'variables.yml'
Read vars_file 'variables.yml'

PLAY [Set NTP server IP] *****************************************************************************************************************************************************************************************************************************
META: ran handlers
Read vars_file 'variables.yml'

TASK [NTP IP] ****************************************************************************************************************************************************************************************************************************************
task path: /root/play2.yml:8
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1588684077.83-32289-26631341423478 && echo ansible-tmp-1588684077.83-32289-26631341423478="` echo /root/.ansible/tmp/ansible-tmp-1588684077.83-32289-26631341423478 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/aruba_instant/arubainstant_config.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-32271PUDkd0/tmp4y45CK TO /root/.ansible/tmp/ansible-tmp-1588684077.83-32289-26631341423478/AnsiballZ_arubainstant_config.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1588684077.83-32289-26631341423478/ /root/.ansible/tmp/ansible-tmp-1588684077.83-32289-26631341423478/AnsiballZ_arubainstant_config.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1588684077.83-32289-26631341423478/AnsiballZ_arubainstant_config.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1588684077.83-32289-26631341423478/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_arubainstant_config_payload_pvbtly/ansible_arubainstant_config_payload.zip/ansible/modules/network/aruba_instant/arubainstant_config.py", line 191, in mm_api_call
[WARNING]: Module did not set no_log for password
fatal: [localhost]: FAILED! => changed=false 
  api_call:
    api_name: ntp-server
    config_path: null
    data:
      ntp-server:
        action: create
        ntp_server_ip: 1.1.1.2
    host: 192.168.100.31
    method: POST
    password: admin123
    url: https://192.168.100.31:4343/rest/ntp-server?sid=wOzXZlC3dbFKfBi3dEMc
    username: admin
  invocation:
    module_args:
      api_name: ntp-server
      api_type: configuration
      data:
        ntp-server:
          action: create
          ntp_server_ip: 1.1.1.2
      host: 192.168.100.31
      iap_ip_addr: null
      method: POST
      password: admin123
      session: null
      username: admin
  msg: API Call failed! Exception during api call
  reason: '''Status'''

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

root@ansible:~# cat play2.yml 
- name: Set NTP server IP
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: NTP IP
      arubainstant_config:
        host: "{{ virtual_controller_ip }}"
        username: "{{ virtual_controller_username }}"
        password: "{{ virtual_controller_password }}"
        method: POST
        api_type: configuration
        api_name: ntp-server
        data: { "ntp-server" : { "action" :"create", "ntp_server_ip" : "1.1.1.2" }}
root@ansible:~#

Is this a Issue with the Playbook or Ansible itself ?
Regards Mac

**Comment by jayp193** [comment]
After the fix, I get the following success message as output of the playbook in verbose mode (-vvv)



    changed: [localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "api_name": "ntp-server", 
            "api_type": "configuration", 
            "data": {
                "ntp-server": {
                    "action": "delete", 
                    "ntp_server_ip": "1.1.1.2"
                }
            }, 
            "host": "10.70.172.250", 
            "iap_ip_addr": null, 
            "method": "POST", 
            "password": "Aruba1234", 
            "session": null, 
            "username": "admin"
        }
    }, 
    "response": "{u'message': u'Success', u'Status-code': 0}", 
    "response_code": 200 }
