### ISSUE TITLE
[Errno 2] arubaoss_rest.py

### ISSUE THREAD

**Issue by oui-bensai** [aruba/aruba-ansible-modules#116]
Hello there, 
I encountering an unlisted problem when I try to install the modules :
`python aruba_module_installer/aruba_module_installer.py

[...]
Copying plugins/doc_fragments/arubaoss_rest.py to /usr/lib/python3/dist-packages/ansible/plugins/doc_fragments/arubaoss_rest.py...

Traceback (most recent call last):
  File "aruba_module_installer/aruba_module_installer.py", line 424, in <module>
    raise e
IOError: [Errno 2] No such file or directory: u'/usr/lib/python3/dist-packages/ansible/plugins/doc_fragments/arubaoss_rest.py'
`
I'm not sure to understand what i'm suppose to do about that .. 
Could someone help me?

- Ansible version : 2.7.7
- Python version : 3.7.3
- OS version : Debian 10

**Comment by tchiapuziowong** [comment]
Hi @oui-bensai we're looking into this error - as a workaround are you able to update your Ansible version to 2.9? This would allow you to install our AOS-Switch Ansible Collection which has all the same functionality and capabilities as our modules here, it just doesn't require you to use the python installer - https://github.com/aruba/aos-switch-ansible-collection

**Comment by oui-bensai** [comment]
I had to reinstall a entire OS because of various python problems that were blocking the Ansible update... 
And it works! I was able to create a remote VLAN on one of my Switches, I will be able to explore the possibilities of this module and I thank you for that ! 

It's possible that the issue mentioned here were related to bad Python configurations. 
As **I'm getting a functional result on Ansible 2.9**,  I'm going to close this ticket, thanks again for your help and have a good day =)
