### ISSUE TITLE
arubaoss_file_transfer upload firmware not working on all switch models

### ISSUE THREAD

**Issue by zenchaos** [aruba/aruba-ansible-modules#119]
Copy of firmware works flawlessly on 2930F but fails on 2920 switches.

ansible-playbook 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/Python/venv2/lib/python3.6/site-packages/ansible
  executable location = /home/ansible/Python/venv2/bin/ansible-playbook
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]

The module won't run at all unless the python path is set as follows.  
ansible_python_interpreter: /home/ansible/Python/venv2/bin/python

I'm setting the variable in a all.yml, other modules don't require this.

      - name: copy image for 2930F
        arubaoss_file_transfer:
          file_url: "http://10.1.1.100/WC_16_10_0010.swi"
          file_type: "FTT_FIRMWARE"
          boot_image: "BI_SECONDARY_IMAGE"
          action: "FTA_DOWNLOAD"
        when: ShowVer is search("WC.16.")

      - name: copy image for 2920
        arubaoss_file_transfer:
          file_url: "http://10.1.1.100/WB_16_10_0010.swi"
          file_type: "FTT_FIRMWARE"
          boot_image: "BI_SECONDARY_IMAGE"
          action: "FTA_UPLOAD"
        when: ShowVer is search("WB.16.")

When this is run against a 2920 with WB.16.10.0005 copy fails with the following error.

TASK [copy image for 2920] *****************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'TypeError'>, a bytes-like object is required, not 'str'
fatal: [XXXSW121]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
  File \"/tmp/ansible_arubaoss_file_transfer_payload_wnzl70o4/ansible_arubaoss_file_transfer_payload.zip/ansible/modules/network/arubaoss/arubaoss_file_transfer.py\", line 188, in run_module
  File \"/tmp/ansible_arubaoss_file_transfer_payload_wnzl70o4/ansible_arubaoss_file_transfer_payload.zip/ansible/modules/network/arubaoss/arubaoss_file_transfer.py\", line 133, in transfer
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"<stdin>\", line 102, in <module>
  File \"<stdin>\", line 94, in _ansiballz_main
  File \"<stdin>\", line 40, in invoke_module
  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_arubaoss_file_transfer_payload_wnzl70o4/ansible_arubaoss_file_transfer_payload.zip/ansible/modules/network/arubaoss/arubaoss_file_transfer.py\", line 199, in <module>
  File \"/tmp/ansible_arubaoss_file_transfer_payload_wnzl70o4/ansible_arubaoss_file_transfer_payload.zip/ansible/modules/network/arubaoss/arubaoss_file_transfer.py\", line 196, in main
  File \"/tmp/ansible_arubaoss_file_transfer_payload_wnzl70o4/ansible_arubaoss_file_transfer_payload.zip/ansible/modules/network/arubaoss/arubaoss_file_transfer.py\", line 190, in run_module
  File \"/tmp/ansible_arubaoss_file_transfer_payload_wnzl70o4/ansible_arubaoss_file_transfer_payload.zip/ansible/module_utils/basic.py\", line 2092, in fail_json
  File \"/tmp/ansible_arubaoss_file_transfer_payload_wnzl70o4/ansible_arubaoss_file_transfer_payload.zip/ansible/module_utils/basic.py\", line 2064, in _return_formatted
  File \"/tmp/ansible_arubaoss_file_transfer_payload_wnzl70o4/ansible_arubaoss_file_transfer_payload.zip/ansible/module_utils/basic.py\", line 418, in remove_values
  File \"/tmp/ansible_arubaoss_file_transfer_payload_wnzl70o4/ansible_arubaoss_file_transfer_payload.zip/ansible/module_utils/basic.py\", line 401, in _remove_values_conditions
TypeError: Value of unknown type: <class 'TypeError'>, a bytes-like object is required, not 'str'
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}

**Comment by alagoutte** [comment]
Hi,

What don't not using the same action ? (FTA_DOWNLOAD & FTA_UPLOAD)

**Comment by tchiapuziowong** [comment]
Hi @zenchaos if you use action FTA_DOWNLOAD for the 2920 does the module function?
