### ISSUE TITLE
Modules not found even though they exist

### ISSUE THREAD

**Issue by g-gill1995** [aruba/aruba-ansible-modules#123]
ERROR! couldn't resolve module/action 'arubanetworks.aos_switch.arubaoss_command'. This often indicates a misspelling, missing collection, or incorrect module path.

I can see ~./ansible/ansible_collections/arubanetworks/aos_switch/plugins/modules/command.py BUT I constantly keep getting this error.

**Comment by tchiapuziowong** [comment]
Hi @g-gill1995 can you please open this issue on our collection repo? https://github.hpe.com/switchautomation/aos-switch-ansible-collection

Also in that post can you share your playbook and the results? Please make sure you have the latest version of the collection installed with the following command: 
`ansible-galaxy collection install arubanetworks.aos_switch -f`

**Comment by g-gill1995** [comment]
Hey,

That link provided below does not work ☹

**Comment by tchiapuziowong** [comment]
Apologies here's the correct link: https://github.com/aruba/aos-switch-ansible-collection

**Comment by g-gill1995** [comment]
Hey,

I have already posted the issue about 4 days ago: https://github.com/aruba/aos-switch-ansible-collection/issues/4

Thanks!
