### ISSUE TITLE
Playbook Execution Failed During Ansible Testing with ArubaOS Switch

### ISSUE THREAD

**Issue by DSIbrahim** [aruba/aruba-ansible-modules#126]
@brasswood 

I have tried to understand your own error message but I'm not sure if it's the same as mine. This is what my own error looks like.

root@ANSBL_HOST ~/.../example_playbooks/arubaoss# ansible-playbook system_attributes.yml -i switch_hosts.yml -vvv
ansible-playbook 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/library', '/usr/share/ansible/library']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.5.3 (default, Jul  9 2020, 13:00:10) [GCC 6.3.0 20170516]
Using /etc/ansible/ansible.cfg as config file
/root/aruba-ansible-modules/example_playbooks/arubaoss/switch_hosts.yml did not meet host_list requirements, check plugin documentation if this is unexpected
/root/aruba-ansible-modules/example_playbooks/arubaoss/switch_hosts.yml did not meet script requirements, check plugin documentation if this is unexpected
Parsed /root/aruba-ansible-modules/example_playbooks/arubaoss/switch_hosts.yml inventory source with yaml plugin

PLAYBOOK: system_attributes.yml *****************************************************************************************************************************
1 plays in system_attributes.yml

PLAY [switch1] **********************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
task path: /root/aruba-ansible-modules/example_playbooks/arubaoss/system_attributes.yml:2
<10.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1608840091.859959-203977037209912 `" && echo ansible-tmp-1608840091.859959-203977037209912="` echo /root/.ansible/tmp/ansible-tmp-1608840091.859959-203977037209912 `" ) && sleep 0'
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/system/setup.py
<10.0.0.1> PUT /root/.ansible/tmp/ansible-local-14915rrdf0vcr/tmpp4osb2uj TO /root/.ansible/tmp/ansible-tmp-1608840091.859959-203977037209912/AnsiballZ_setup.py
<10.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1608840091.859959-203977037209912/ /root/.ansible/tmp/ansible-tmp-1608840091.859959-203977037209912/AnsiballZ_setup.py && sleep 0'
<10.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1608840091.859959-203977037209912/AnsiballZ_setup.py && sleep 0'
<10.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1608840091.859959-203977037209912/ > /dev/null 2>&1 && sleep 0'
ok: [switch1]
META: ran handlers

TASK [Update Switch System Attributes] **********************************************************************************************************************
task path: /root/aruba-ansible-modules/example_playbooks/arubaoss/system_attributes.yml:4
<10.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112 `" && echo ansible-tmp-1608840092.9190829-177993150277112="` echo /root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112 `" ) && sleep 0'
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/network/arubaoss/arubaoss_system_attributes.py
<10.0.0.1> PUT /root/.ansible/tmp/ansible-local-14915rrdf0vcr/tmp4_x8plwj TO /root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/AnsiballZ_arubaoss_system_attributes.py
<10.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/ /root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/AnsiballZ_arubaoss_system_attributes.py && sleep 0'
<10.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/AnsiballZ_arubaoss_system_attributes.py && sleep 0'
<10.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/AnsiballZ_arubaoss_system_attributes.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/AnsiballZ_arubaoss_system_attributes.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/AnsiballZ_arubaoss_system_attributes.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_arubaoss_system_attributes_payload_vsEd5V/__main__.py", line 90, in <module>
  File "/tmp/ansible_arubaoss_system_attributes_payload_vsEd5V/ansible_arubaoss_system_attributes_payload.zip/ansible/module_utils/network/arubaoss/arubaoss.py", line 44, in <module>
ImportError: No module named utils.display

fatal: [switch1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/AnsiballZ_arubaoss_system_attributes.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/AnsiballZ_arubaoss_system_attributes.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1608840092.9190829-177993150277112/AnsiballZ_arubaoss_system_attributes.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_arubaoss_system_attributes_payload_vsEd5V/__main__.py\", line 90, in <module>\n  File \"/tmp/ansible_arubaoss_system_attributes_payload_vsEd5V/ansible_arubaoss_system_attributes_payload.zip/ansible/module_utils/network/arubaoss/arubaoss.py\", line 44, in <module>\nImportError: No module named utils.display\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
        to retry, use: --limit @/root/aruba-ansible-modules/example_playbooks/arubaoss/system_attributes.retry

PLAY RECAP **************************************************************************************************************************************************
switch1                    : ok=1    changed=0    unreachable=0    failed=1

Any ideas, please?

**Comment by alagoutte** [comment]
Hi,

Can you update ansible version ? there is this warning _ImportError: No module named utils.display_ and this module is available with last ansible version

**Comment by DSIbrahim** [comment]
Thanks Alexis @alagoutte 

Updating Ansible to the new version (2.10.4) did the trick.
