### ISSUE TITLE
CONTRIBUTING.md "Aruba Bots Automate Videos" Playlist Link does not exist

### ISSUE THREAD

**Issue by pixeldoc2000** [aruba/aruba-ansible-modules#128]
Link to "Aruba Bots Automate Videos" Playlist is not working (anymore).

Link should point to [Aruba Bots Automate Videos](https://www.youtube.com/playlist?list=PLsYGHuNuBZcY02FUh95ZpOB5VFkPurVaX) .

**Comment by tchiapuziowong** [comment]
Thank you for finding this! Fixed in https://github.com/aruba/aruba-ansible-modules/commit/7b49496e28ca6dcef64ccc437f3c3ae9fa82e1a6
