### ISSUE TITLE
dhcp snooping parameters

### ISSUE THREAD

**Issue by fallenfuzz** [aruba/aruba-ansible-modules#13]
Would be nice to have dhcp-snooping parameters.
Thanks

**Comment by zenchaos** [comment]
We need to enable dhcp-snooping too.  That is the mechanism used to identify client IP address for radius accounting.

**Comment by tchiapuziowong** [comment]
Hi @fallenfuzz and @zenchaos !

I'm happy to announce we've created [a new module for configuring DHCP snooping](https://github.com/aruba/aruba-ansible-modules/blob/master/module_documentation/arubaoss/arubaoss_dsnoop.md)

I welcome you to try it out and if you find any problems please open a new Github issue!

https://github.com/aruba/aruba-ansible-modules/commit/149b9dd3c084b25842c779e6be230e741f070576
