### ISSUE TITLE
How to automate Cisco ios switch backup to tftp server using ansible

### ISSUE THREAD

**Issue by k-ramesh-9** [aruba/aruba-ansible-modules#132]
I have tried
ios_command module to run command
"copy running-config tftp"
Next I have to provide ip of tftp server. 
I have tftp server running and I have ip address of it. But to provide the ip address. 
I have tried with sending
ios_command;
  commands:
  -copy running-config tftp
  -ip of my tftp server.

It didn't worked
Can anyone help me?

**Comment by karthikeyan-dhandapani** [comment]
Hi @k-ramesh-9,

You have posted an issue that is not related to Aruba's modules. We do not have a module name "ios_command". Please direct your question to the appropriate channel.

Thanks
