### ISSUE TITLE
Connecting 2 Aruba 2930M switches together. Plug and play??

### ISSUE THREAD

**Issue by aamore** [aruba/aruba-ansible-modules#27]
Hi all,

I recently configured two Aruba 2930M switches and am trying to deploy them. I am having trouble connecting both switches together. I was under the impression that it was plug and play. Below is a picture of the setup:
![arubapic](https://user-images.githubusercontent.com/51163236/59632713-d331a700-9118-11e9-9843-b248221ba50a.jpg)
As you can see, I have a fiber-optic cable on the right side connecting the two switches. The orange lights are currently blinking, which I assume means that they aren't properly connected or there is something on each switch I need to configure.

I have tried manipulating the connection and restarted both switches just in case and it did not help. Any help would be greatly appreciated! The manual doesn't tell me much!

**Comment by tchiapuziowong** [comment]
Hi @aamore !
I'm sorry to hear your 2930M setup is not functioning as expected, I'm not sure where the Ansible modules are being used in this setup. If you're having trouble using the modules and Ansible, what exactly are your outputs/errors?

If you're not using Ansible or the Aruba switching modules, I would recommend posting on the Airheads Campus Switching Community! I'm sure you'll find a prompt response to help troubleshoot your issue!

Link to community: https://community.arubanetworks.com/t5/Wired-Intelligent-Edge-Campus/bd-p/CampusSwitching

Thanks!

**Comment by aamore** [comment]
So far, there are no errors other than the blinking lights. I actually tried to connect the switches via ethernet ports and it works fine. Guess I didn't even need the fiber optic cables! Thanks for the help!
