### ISSUE TITLE
vlan module

### ISSUE THREAD

**Issue by fallenfuzz** [aruba/aruba-ansible-modules#3]
arubaoss_vlan
  not able to create vlan, gives error bellow. tried different options from examples, same result.

  deleting vlan worked just fine!

arubaoss_system_attributes
  worked fine for changing hostname

fatal: [switch1]: FAILED! => {
    "body": "{\"message\":\"Invalid parameters\"}",
    "changed": false,
    "connection": "close",
    "content-type": "application/json",
    "invocation": {
        "module_args": {
            "acl_direction": null,
            "acl_id": null,
            "acl_type": "AT_STANDARD_IPV4",
            "api_version": "v5.0",
            "command": "config_vlan",
            "config": "create",
            "helper_addresses": "",
            "host": "switch",
            "ip_address_mode": "IAAM_STATIC",
            "is_dhcp_server_enabled": false,
            "is_dsnoop_enabled": false,
            "is_jumbo_enabled": false,
            "is_management_vlan": false,
            "is_voice_enabled": false,
            "name": "vlan300",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 80,
            "port_id": "",
            "port_mode": "POM_UNTAGGED",
            "provider": {
                "api_version": null,
                "host": "switch",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 80,
                "ssh_keyfile": null,
                "timeout": 10,
                "transport": "aossapi",
                "use_proxy": false,
                "use_ssl": false,
                "username": "Admin",
                "validate_certs": false
            },
            "qos_policy": null,
            "ssh_keyfile": null,
            "status": "VS_PORT_BASED",
            "timeout": 10,
            "use_ssl": false,
            "username": "Admin",
            "validate_certs": false,
            "version": "IAV_IP_V4",
            "vlan_id": 300,
            "vlan_ip_address": "",
            "vlan_ip_mask": "",
            "vlantype": "VT_STATIC"
        }
    },
    "msg": "HTTP Error 400: Bad Request",
    "requestid": "",
    "server": "eHTTP v2.0",
    "status": 400,
    "transfer-encoding": "chunked",
    "url": "http://switch:80/rest/v5.0/vlans"
}

**Comment by alagoutte** [comment]
What your switch firmware ?

**Comment by fallenfuzz** [comment]
tried 16.06 and 16.08

**Comment by fallenfuzz** [comment]
found the issue.
Once commented this all worked:
under def config_vlan(module):
     data['status'] = params['status']
    data['type'] = params['vlantype']
    data['is_jumbo_enabled'] = params['is_jumbo_enabled']
    data['is_voice_enabled'] = params['is_voice_enabled']
    data['is_dsnoop_enabled'] = params['is_dsnoop_enabled']
    #data['is_dhcp_server_enabled'] = params['is_dhcp_server_enabled']
    data['is_management_vlan'] = params['is_management_vlan']


under def run_module():
        is_jumbo_enabled=dict(type='bool', required=False, default=False),
        is_voice_enabled=dict(type='bool', required=False, default=False),
        is_dsnoop_enabled=dict(type='bool', required=False, default=False),
       # is_dhcp_server_enabled=dict(type='bool', required=False, default=False),
        is_management_vlan=dict(type='bool', required=False, default=False),
        vlan_ip_address=dict(type='str', required=False, default=""),

**Comment by tchiapuziowong** [comment]
Hi what does your task look like? i.e. where you call the module?

**Comment by fallenfuzz** [comment]
@tchiapuziowong simple taks to create VLAN.
That is for sure is_dhcp_server_enabled related since the switch I'm running task on doesn't support it.
Once that commented - all works as expected.

I'll try to run on switch that supports that

**Comment by fallenfuzz** [comment]
@tchiapuziowong 
So after a test and uncommented data['is_dhcp_server_enabled'] = params['is_dhcp_server_enabled']
Aruba 2530 - doesn't work (Switch doesn't support dhcp server)
Aruba 2930F - works since it is supporting dhcp server.

**Comment by clydeb** [comment]
@fallenfuzz thanks for troubleshooting, I ran into the same issue and can confirm that commenting out the line "data['is_dhcp_server_enabled'] = params['is_dhcp_server_enabled']" makes it work again for Aruba 2530.

**Comment by tchiapuziowong** [comment]
thank you @fallenfuzz for providing that solution! I'll work on a way to properly document that, once it's up I'll close this issue!
