### ISSUE TITLE
Get facts from arubaoss

### ISSUE THREAD

**Issue by cirola2000** [aruba/aruba-ansible-modules#44]
Hello everyone,

Is there somehow a way to get facts from arubaoss switches? For instance, I'd like to know the switch model or the os version. 

Many thanks!

**Comment by tchiapuziowong** [comment]
Hello! At this time we don't have any "gather_facts" support for our network modules, we do have the option of using the [SSH CLI module](https://community.arubanetworks.com/t5/Developer-Community/How-to-install-use-CLI-modules-and-tasks-for-Switch-and-CX-in/td-p/534333) for show commands but then you'll have to parse the info. 

I'll mark this as an enhancement so while we're working on the AOS-Switch Role for Galaxy, maybe we can include this.

**Comment by 11gingerbread** [comment]
Any update on this enhancement request ? I need the same too.

**Comment by tchiapuziowong** [comment]
@cirola2000 I am so happy to finally announce we've done it! Check out our arubaoss_facts module in the latest version of our collection: https://galaxy.ansible.com/arubanetworks/aos_switch
