### ISSUE TITLE
msg: AOS-Switch Ansible support needs minimum Firmware version of 16.08.xx

### ISSUE THREAD

**Issue by fallenfuzz** [aruba/aruba-ansible-modules#54]
Hi,

Anyway to run 16.05 and 16.06? I'm sure it was possible to run on lower then 16.08 versions.
If not , would be wise mentioning that on the main page 😇

Thanks

**Comment by tchiapuziowong** [comment]
Hi @fallenfuzz ! The modules are written for 16.08 firmware version and above. Although some modules may have supportability for 16.06, there are REST API functionalities introduced in 16.08 that are not supported in previous versions. Apologies for any convenience and [the README has been updated to reflect this restriction ](https://github.com/aruba/aruba-ansible-modules/commit/50030f955fe6ca4923b8b3fae1bf404ec3270953)
