### ISSUE TITLE
Copy Paste Error in SNMP 

### ISSUE THREAD

**Issue by Pack3tL0ss** [aruba/aruba-ansible-modules#6]
module_documentation/arubaoss/arubaoss_snmp.md has an error per closed pull request (told to submit an issue instead of PR), I believe is was just a copy/paste error (stanza appeared multiple times).

refer to rejected pull request for details

**Comment by tchiapuziowong** [comment]
Thank you for raising this issue! I've fixed the module parameters as well as the examples in commit: 00fe6a642d530f0f84cc64e3465a0f6ca6762f16
Closing issue.
