### ISSUE TITLE
CPPM : Name 'result' is not defined, in exit_json() for GET requests.

### ISSUE THREAD

**Issue by sachaboudjema** [aruba/aruba-ansible-modules#62]
https://github.com/aruba/aruba-ansible-modules/blob/f494294dc4ff7b947630e83bd3811c2a11e8cb7a/aruba_module_installer/library/modules/network/aruba_clearpass/arubaclearpass_config.py#L165

Should be 'resp.msg' as in POST case

**Comment by karthikeyan-dhandapani** [comment]
The respective PR is verified and merged. Closing this issue.

@sachaboudjema Thanks for the contribution.
