### ISSUE TITLE
SSH/Telnet

### ISSUE THREAD

**Issue by wazzfi** [aruba/aruba-ansible-modules#69]
can we do the following with Ansible:

1. disable telnet
2. enabled SSH

?

**Comment by tchiapuziowong** [comment]
Hi @wazzfi!

At this moment our Ansible modules for AOS-Switch do not currently support disabling telnet and we don't have REST API support for enabling SSH. If you're able to use SSH though I would suggest using our SSH modules [arubaoss_command](https://github.com/aruba/aruba-ansible-modules/blob/master/module_documentation/arubaoss/arubaoss_command.md) and [arubaoss_config](https://github.com/aruba/aruba-ansible-modules/blob/master/module_documentation/arubaoss/arubaoss_config.md). To install these latest modules [follow these steps](https://github.com/aruba/aruba-ansible-modules#how-to-install-updates-or-new-modules). If you want to use a combination of both using REST API modules and SSH, I suggest reading this blurb about [using both REST API and SSH/CLI modules](https://github.com/aruba/aruba-ansible-modules#using-both-rest-api-and-sshcli-modules-on-a-host).
