### ISSUE TITLE
arubaoss :: cppm_details

### ISSUE THREAD

**Issue by wazzfi** [aruba/aruba-ansible-modules#71]
Hey crew

This still doesnt work -- comes up with an error "mising username in cppm_details"

(2930F running 10.09)

    - name: Configure Radius Profile CPPM details for User Roles
      arubaoss_radius_profile:
        command: config_radius_profile
        cppm_details: {'username':'superman','password': 'upupandaway'}

**Comment by tchiapuziowong** [comment]
Hi wazzfi did you pull the repo to receive the commit ae0fbe85ab8b17a3ee3d3a4a44e76eefe5285037 and re-install the modules with the following command `python aruba_module_installer.py --reinstall` ?

**Comment by wazzfi** [comment]
same error even after the update.

I rebooted my laptop too (not sure if that helps but hey...why not).

**Comment by tchiapuziowong** [comment]
Verified issue with user was due to lack of executing 'git pull' before re-installing modules - closing issue
