### ISSUE TITLE
arubaoss :: 802.1X config

### ISSUE THREAD

**Issue by wazzfi** [aruba/aruba-ansible-modules#72]
This doesnt want to run either: apparently an issue with the " -name" line of the config?

     - name: 802.1X port-access config
       arubaoss_aaa_dot1x:
         is_dot1x_enabled: true
         server_group: "CPPM_Mgmt_IF"
         primary_authentication_method: DPAM_EAP_RADIUS
         allow_gvrp_vlans: true
         is_authenticator_enabled: True
         allow_mixed_users: True
         supplicant_timeout: 10
         tx_period: 10

**Comment by tchiapuziowong** [comment]
Hi @wazzfi , the module name is arubaoss_dot1x - https://github.com/aruba/aruba-ansible-modules/blob/master/aruba_module_installer/library/modules/network/arubaoss/arubaoss_dot1x.py

try fixing the module name and see if that resolves your issue

**Comment by wazzfi** [comment]
nailed in 

Thanks mate :)
