### ISSUE TITLE
aruba_command no output on HP J9776A 2530-24G Switch

### ISSUE THREAD

**Issue by erishiamu** [aruba/aruba-ansible-modules#74]
Hi, 

I was referred to post here by an MVP on the airheads community board. I am trying to use the aruba_command module both in playbook and adhoc to pull information from a 2530-24g switch. Per aruba's support this model does not support the api so I'm forced to use the aruba_command module. 

adhoc cmds with the respective change to connectiontype made in the hosts file. I've also tried raw, same result. 

ansible SWITCHNAME -m aruba_command -a "commands='show running-config'" -c local -u SERVICEACCOUNT -k
ansible SWITCHNAME -m cli_command -a "commands='show running-config'" -c local -u SERVICEACCOUNT -k

I receive this output: https://i.postimg.cc/fRcNbWzp/Untitled.png, connection is successful but no information is returned. This has applied to multiple show commands.

**Comment by erishiamu** [comment]
We've abandoned trying to back this up programmatically due to a lack of support from HP/Aruba and that these are (fortunately) static. Closing.

**Comment by tchiapuziowong** [comment]
Hi @erishiamu , 

I'm sorry for your frustration, the aruba_command is a module designed for the Mobility Master controller and not for an AOS-Switch. It appears you're already using the proper modules in issue #76 . Let's continue on that issue for troubleshooting.
