### ISSUE TITLE
How to use AnyCLI

### ISSUE THREAD

**Issue by louisfrancoisSO** [aruba/aruba-ansible-modules#8]
Hello again,

I'm starting to work more with your modules and I have questions on what's possible or not.
In Aruba v16.04, there are new functionnalities AnyCLI and Batch_CLI.
Those REST API functions are quite useful and I was wondering if it was possible to use them in your module.

FYI, the URI is  `http(s)://IP/rest/v3/cli`
with a JSON 

> { "cmd" : "<your_cmd>" }

For example, I would like do `show version` on my switchs.
So something like
```---
- host: switch1
tasks: 
  - name: show version
    aruba_cli: 
      cmd: show version
```

So first, is it possible to use it? I have not seen it in the different files on the Git
If not, how to get info like this?

Thank you,

Louis

**Comment by alagoutte** [comment]
it is possible to have a API for get directly version (like rest/vX/system...)

**Comment by tchiapuziowong** [comment]
Hi!

There are a couple options to using AnyCli or even SSH CLI. Please see this post on our Airheads Developer Community! https://community.arubanetworks.com/t5/Developer-Community/How-to-install-use-CLI-modules-and-tasks-for-Switch-and-CX-in/td-p/534333

For 'How-To' questions, please use this forum as a resource! 

Thanks!

**Comment by louisfrancoisSO** [comment]
Hello,

The post you sent use another github project.
Yours is way simpler so I would prefer to keep everything in here.
Moreover the inventories are different in both projects so it is not possible to use both at the same time for the same targets. That's why I was asking.

> it is possible to have a API for get directly version (like rest/vX/system...)
Yes but my goal is to use Ansible, that will use the API (or via SSH).

**Comment by tchiapuziowong** [comment]
You don't need to use the whole project, just simply the modules in the project. The inventory in this Github can work with the modules from the other Github. Modules in Ansible are not dependent on the inventory. 
To use the SSH modules, you can copy the library directory from the

**Comment by tchiapuziowong** [comment]
You don't need to use the whole project, just simply the modules in the project. The inventory in this Github can work with the modules from the other Github. Modules in Ansible are not dependent on the inventory.
To use the SSH modules, you can copy the library directory from the
