### ISSUE TITLE
Where are the urls/uris documented

### ISSUE THREAD

**Issue by Powersquids** [aruba/aruba-ansible-modules#80]
Where do i find all these? spent most of the day tooling around on the web and can't seem to find them. I pulled the json schema but i have no idea what configuation entities they're tied to. 
![2020-02-13_17-44-21](https://user-images.githubusercontent.com/9522121/74494277-61695300-4e89-11ea-9e55-d734df2efc37.png)

**Comment by alagoutte** [comment]
Hi,

You need to go on ASP, there is API Rest Guide https://asp.arubanetworks.com/downloads/documents/RmlsZTo4Nzc0ZmJhMi05OWJkLTExZTktYWI5YS00NzJkYTJmYmY1NDk%3D

and there is also a zip with json file

**Comment by Powersquids** [comment]
So I already have the json. As for the API Rest Guide(s), is there like a master one? I've been through several of the guides and haven't found one. I just end up finding small chunks in the change log.
![image](https://user-images.githubusercontent.com/9522121/74557958-2e20d580-4f16-11ea-9b52-f9de8fcc179f.png)

**Comment by alagoutte** [comment]
Do you have look this zip https://h10145.www1.hpe.com/downloads/DownloadSoftware.aspx?SoftwareReleaseUId=27125&ProductNumber=JL557A&lang=&cc=&prodSeriesId=&SaidNumber=

there is a full JSON file...

**Comment by mi138** [comment]
After downloading the above, this link is worth a read ... https://community.arubanetworks.com/t5/Developer-Community/Where-is-the-REST-documentation-for-the-AOS-Switch/m-p/455341

**Comment by tchiapuziowong** [comment]
Hi @Powersquids ! @mi138 is correct this is the best article that describes how to find REST uri's:
https://community.arubanetworks.com/t5/Developer-Community/Where-is-the-REST-documentation-for-the-AOS-Switch/m-p/455341

You'll want to open the **.html** files in  **device-rest-api/services/wired folder** and the **device-rest-api/services/common** folder.

**Comment by Powersquids** [comment]
Ah yep. That's what i was looking for.
