### ISSUE TITLE
NTP module porblems

### ISSUE THREAD

**Issue by zenchaos** [aruba/aruba-ansible-modules#81]
When the following ran on two different switches with the same firmware version, the module worked differently.  On a 2930F, the code ran find, on a 2920, the module failed.

    - name: configure timesync to be ntp
      arubaoss_ntp:
        command: "config_timesync"
        timesyncType: ntp

    - name: Enable NTP in Unicast
      arubaoss_ntp:
        command: "config_ntp"
        config: create
        operate: "unicast"

    - name: configure ntp server 10.1.1.1
      arubaoss_ntp:
        command: "config_ntp_ipv4addr"
        ntp_ip4addr: "10.1.1.1"
        mode: "iburst"

    - name: configure ntp server 10.1.1.2
      arubaoss_ntp:
        command: "config_ntp_ipv4addr"
        ntp_ip4addr: "10.1.1.2"
        mode: "iburst"

2920 firmware
Image stamp:    /ws/swbuildm/rel_ajanta_qaoff/code/build/anm(swbuildm_rel_ajanta_qaoff_rel_ajanta)
                Jan 17 2020 05:52:16
                WB.16.10.0003

rest debug from the switch:
0004:01:20:22.99 rest RestSrv-2:Method = GET, URI = /rest/v7.0/config/timesync
0004:01:20:22.99 rest mrest_ctrl:read len 206
0004:01:20:22.99 rest RestSrv-2:Redirection URL = /rest/v6/config/timesync
0004:01:20:22.99 rest RestSrv-2:Method = GET, URI = /rest/v6/config/timesync
0004:01:20:23.00 rest RestSrv-2:status = 404, reason = Not Found

If NTP is enabled for multicast, the module doesn't sees that ntp is configured and won't set unicast.  ntp has to be disabled then enabled with unicast to configure unicast.  This makes it impossible to verify unicast configuration on the switch.

**Comment by tchiapuziowong** [comment]
Hi @zenchaos ! The 2920 platform does not have the REST API support for configuring NTP. I've documented this limitation in the module_documentation/ for this module . https://github.com/aruba/aruba-ansible-modules/commit/7838b7f2d77036dc0236e3cc387ba4ddd10e65f3

**Comment by tchiapuziowong** [comment]
Hi @zenchaos !

As an update, we just published modules with SSH/CLI command support for the AOS-Switch platform! So if you're able to use SSH though I would suggest using our SSH modules [arubaoss_command](https://github.com/aruba/aruba-ansible-modules/blob/master/module_documentation/arubaoss/arubaoss_command.md) and [arubaoss_config](https://github.com/aruba/aruba-ansible-modules/blob/master/module_documentation/arubaoss/arubaoss_config.md). To install these latest modules [follow these steps](https://github.com/aruba/aruba-ansible-modules#how-to-install-updates-or-new-modules). If you want to use a combination of both using REST API modules and SSH, I suggest reading this blurb about [using both REST API and SSH/CLI modules](https://github.com/aruba/aruba-ansible-modules#using-both-rest-api-and-sshcli-modules-on-a-host).
