### ISSUE TITLE
arubaoss_vlan can't set ip or helper addresses

### ISSUE THREAD

**Issue by zenchaos** [aruba/aruba-ansible-modules#88]
I'm trying to create vlans on a 3810 switch that will be gateways for a building.  The following will create the vlan and name it but that's all.  We need a string of helper addresses for dhcp servers, clearpass nodes and netboot servers.

How do I set the address and helpers?

    - name: Configure client vlan
      arubaoss_vlan:
        vlan_id: "{{ client_vlan }}"
        name: "VLAN{{ client_vlan_name }}"
        status: "VS_PORT_BASED"
        vlantype: "VT_STATIC"
        ip_address_mode: IAAM_STATIC
        vlan_ip_address: "{{ client_sw1_ip }}"
        vlan_ip_mask: "{{ client_mask }}"
        helper_addresses: "10.1.1.10, 10.1.1.11, 10.1.1.12, 10.1.1.110, 10.1.1.111, 10.1.1.112"
        config: "create"
        command: config_vlan

**Comment by zenchaos** [comment]
Configuring the name of a vlan with an IP helper set throws an error.  Is there a way to change or set a vlan name?

    - name: Configure Client vlan
      arubaoss_vlan:
        vlan_id: "{{ client_vlan }}"
        name: "VLAN{{ client_vlan }}"
        status: "VS_PORT_BASED"
        vlantype: "VT_STATIC"
        config: "create"
        command: config_vlan

-----------------------------------------------------------------------------------

TASK [arubaoss_vlan : Configure Client vlan] ****************************************************************************************
fatal: [TestSwitch]: FAILED! => {"body": "{\"message\":\"DHCP relay should be un-configured(helper address)on this VLAN to configure DHCP server.\"}", "changed": false, "connection": "close", "content-type": "application/json", "msg": "HTTP Error 400: Bad Request", "requestid": "", "server": "eHTTP v2.0", "status": 400, "transfer-encoding": "chunked", "url": "http://10.253.10.1:80/rest/v7.0/vlans/10"}

**Comment by tchiapuziowong** [comment]
Hi @zenchaos !

It looks like you're attempting to configure multiple VLAN configurations in one task when we actually want to separate each configuration in a corresponding task, for your initial issue this would be the playbook equivalent (you'll need to add more tasks for head dhcp helper address you want to configure:

      - name: Configure client vlan
        arubaoss_vlan:
          vlan_id: 16
          name: "vlan16"
          status: "VS_PORT_BASED"
          vlantype: "VT_STATIC"

      - name: Config IP - notice the command field
        arubaoss_vlan:
          vlan_id: 16
          ip_address_mode: IAAM_STATIC
          vlan_ip_address: 16.1.1.1
          vlan_ip_mask: 255.255.255.0
          command: config_vlan_ipaddress

      - name: Config helper address 1 - notice command field
        arubaoss_vlan:
          vlan_id: 16
          helper_addresses: 10.1.1.10
          config: "create"
          command: config_vlan_dhcpHelperAddress

      - name: Config helper address 2 - notice command field
        arubaoss_vlan:
          vlan_id: 16
          helper_addresses: 10.1.1.11
          config: "create"
          command: config_vlan_dhcpHelperAddress

      - name: Config helped address 3 - notice command field
        arubaoss_vlan:
          vlan_id: 16
          helper_addresses: 10.1.1.12
          config: "create"
          command: config_vlan_dhcpHelperAddress
