### ISSUE TITLE
how to remove sntp server command from config

### ISSUE THREAD

**Issue by hrv231** [aruba/aruba-ansible-modules#9]
Hello,

As the subject says, I would like to be able to remove the "sntp server priority 1 X.X.X.X" from my config, either using cli or API, but I don't know how to do it with the module.

**Comment by alagoutte** [comment]
hi

From cli, you can use no sntp server X.X.X.X ?

**Comment by hrv231** [comment]
Hi,

That's not my question, I know how to do this from cli, but I want to use this with ansible to be able to remove it from a list of devices.
How can I accomplish this with your module ?

**Comment by tchiapuziowong** [comment]
Hello!

I'm currently researching how to accomplish this with our current modules, but in the mean time, you can look into using either a AnyCli REST call or an SSH CLI command. Please see this post on our Airheads Developer Community! https://community.arubanetworks.com/t5/Developer-Community/How-to-install-use-CLI-modules-and-tasks-for-Switch-and-CX-in/td-p/534333

**Comment by hrv231** [comment]
Thank you @tchiapuziowong , hopefully this will be added to the module soon.
Thank you also for the link, I was having some trouble using the modules and samples from:
**https://github.com/aruba/aruba-switch-ansible**

**Comment by FloLaco** [comment]
Actually you can't do this in Ansible, neither with these modules neither with the URI module because the uri `/system/sntp` does not support the `DELETE` method, only GET and PUT.
HPE need to update their OS before Ansible can do something

**Comment by alagoutte** [comment]
@FloLaco do you have try to PUT a empty value ? (for /system/sntp) work for some "URI"

**Comment by tchiapuziowong** [comment]
Hi all! we now have a new SNTP module for AOS-Switch that will allow you to remove SNTP server priority configurations as well as SNTP configurations, at this time only IPv4 SNTP servers are supported through REST API
https://github.com/aruba/aruba-ansible-modules/commit/3e2af1688ffa5eb12b476a127051c9bfdcd47cbd
