### ISSUE TITLE
Distribute modules and plugins as collection

### ISSUE THREAD

**Issue by Scorcerer** [aruba/aruba-ansible-modules#91]
Hello,
for some time there's a possibility to distribute additional modules and plugins to ansible via colections.
Are there any plans to do it for ansible modules?

**Comment by karthikeyan-dhandapani** [comment]
Hi @Scorcerer, 

Thanks for the feedback!

Checkout the ansible galaxy page for roles and collections that are available today.
https://galaxy.ansible.com/arubanetworks

We are working creating more collections and roles.

**Comment by sachaboudjema** [comment]
I think this repository should be split into multiple platform-specific repositories.
Each repo should support Ansible Galaxy publication to make both editing, versioning and usage easier and more consistent.

I'm willing to help with this if necessary.

**Comment by tchiapuziowong** [comment]
Hi @Scorcerer + @sachaboudjema !

I'm happy to announce we've published our collection for our AOS-Switch platform to galaxy : https://galaxy.ansible.com/arubanetworks/aos_switch

Happy automating! 💯
