### ISSUE TITLE
more Examples for Instant Access

### ISSUE THREAD

**Issue by mac0815** [aruba/aruba-ansible-modules#92]
Hi 
Could you please provide more examples for Instant Access AP Configuration ?

**Comment by alagoutte** [comment]
Hi,

You can look the API IAP Rest Guide => https://asp.arubanetworks.com/downloads/documents/RmlsZTplNWRjNDE2Mi0wZDVhLTExZWEtODg5NC0xZjllNGE3NGE5MWQ%3D

**Comment by mac0815** [comment]
Hi
This examples are curl based and do work if you adapt it to ansible

**Comment by jayp193** [comment]
We will be publishing some more example playbooks for Aruba Instant soon. Stay tuned.
