### ISSUE TITLE
playbook seems to work but Ansible shows an error

### ISSUE THREAD

**Issue by mac0815** [aruba/aruba-ansible-modules#93]
Hi 
my playbook looks like this
- name: Show existing network
  hosts: aruba_ap315
  connection: local
  gather_facts: no
  tasks:
    - name: Show existing network as a show command through API
      arubainstant_config:
        host: 192.168.100.31
        username: admin
        password: admin123
        method: POST
        api_type: action
        api_name: hostname
        data: { "iap_ip_addr": "192.168.100.31", "hostname_info": {"hostname": "AP-31"}}
~                                                                                                      
and is seems to work because it changes the Hostname , but Ansible shows me a error

root@ansible:~# ansible-playbook play1.yml -i /etc/ansible/hosts -vv
ansible-playbook 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: play1.yml ********************************************************************************************************************************************************************************************************************************************************
1 plays in play1.yml

PLAY [Show existing network] ***********************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Show existing network as a show command through API] *****************************************************************************************************************************************************************************************************************
task path: /root/play1.yml:6
[WARNING]: Module did not set no_log for password
[WARNING]: Platform linux on host 192.168.100.31 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
fatal: [192.168.100.31]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  api_call:
    api_name: hostname
    config_path: null
    data:
      hostname_info:
        hostname: AP-31
      iap_ip_addr: 192.168.100.31
    host: 192.168.100.31
    method: POST
    password: admin123
    url: https://192.168.100.31:4343/rest/hostname?sid=YJPfZXOw0yoOQxdtJit4
    username: admin
  msg: API Call failed! Exception during api call
  reason: '''Status'''

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************
192.168.100.31             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

root@ansible:~# 

something wrong with the playbook ?

**Comment by alagoutte** [comment]
Hi Mac0815,

You don't have forget the line 'arubaiap_config:' ?
https://github.com/aruba/aruba-ansible-modules/blob/master/aruba_module_installer/library/modules/network/aruba_instant/arubainstant_config.py#L70

**Comment by mac0815** [comment]
Hi
There is no module arubaiap_config available 
I guess someone renamed it to  arubainstant_config ??
Regards Mac

**Comment by nikunj1210** [comment]
Apologies for the confusion. The module was renamed to "arubainstant_config" and documentation section at the top of the file wasn't updated. We will fix that.

We are also working on fixing the main issue on this thread. It seems to be a bug in the code.
