### ISSUE TITLE
Unable to Assign QoS Priority on 2530 Switch

### ISSUE THREAD

**Issue by snjjones1** [aruba/aruba-ansible-modules#94]
I am trying to assign a QoS priority to the VLAN.  However, after running the playbook, the QoS is not present.

Here's the relevant section from the playbook:
`    - name: Create Mgmt VLAN 10
      arubaoss_vlan:
        vlan_id: 10
        name: "Mgmt VLAN"
        config: "create"
        command: config_vlan
        qos_policy: "7"`

On the CLI, I would typically just type: "qos priority 7" while configuring the specific VLAN.

**Comment by alagoutte** [comment]
Hi,

What do you have on ansible output ?

**Comment by tchiapuziowong** [comment]
Hi @snjjones1 !

Can you post the error/output you're receiving? Also what firmware version are you using on your 2530?

**Comment by tchiapuziowong** [comment]
closing issue for now, please re-open with the output 👍
